logging:
  level:
    com:
      example:
        commentservice: DEBUG
spring:
  application:
    name: comment-service
  #      uri: mongodb://localhost:27017/commentdb
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

