name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: build app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#      run: mvb -B verify sonar:sonar -Dsonar.projectkey=malu900_comment-service -Dsonar.host.ur=https://sonarcloud.io -Dsonar.login=d397b23eb0dfbb6081f12b9143d454bc1c3cef2d
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=malu900_comment-service --debug


    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven test
      run: mvn test
    - name: Maven Verify
      run: mvn -B clean verify
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
  deploy:
    name: deploy app
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        TIME_STAMP: $(date +%s)
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: build the docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/comment-service
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/comment-service
